// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"
)

type Url struct {
	ID          int32     `json:"id"`
	UrlOriginal string    `json:"url_original"`
	ShortCode   string    `json:"short_code"`
	AccessCount int32     `json:"access_count"`
	CreatedAt   time.Time `json:"created_at"`
}
