// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"
)

const createURL = `-- name: CreateURL :one
INSERT INTO urls (url_original, short_code)
VALUES ($1, $2)
RETURNING id, url_original, short_code, access_count, created_at
`

type CreateURLParams struct {
	UrlOriginal string `json:"url_original"`
	ShortCode   string `json:"short_code"`
}

func (q *Queries) CreateURL(ctx context.Context, arg CreateURLParams) (Url, error) {
	row := q.db.QueryRowContext(ctx, createURL, arg.UrlOriginal, arg.ShortCode)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.UrlOriginal,
		&i.ShortCode,
		&i.AccessCount,
		&i.CreatedAt,
	)
	return i, err
}

const deleteURL = `-- name: DeleteURL :exec
DELETE FROM urls
WHERE short_code = $1
`

func (q *Queries) DeleteURL(ctx context.Context, shortCode string) error {
	_, err := q.db.ExecContext(ctx, deleteURL, shortCode)
	return err
}

const getURLByShortCode = `-- name: GetURLByShortCode :one
SELECT id, url_original, short_code, access_count, created_at FROM urls
WHERE short_code = $1 LIMIT 1
`

func (q *Queries) GetURLByShortCode(ctx context.Context, shortCode string) (Url, error) {
	row := q.db.QueryRowContext(ctx, getURLByShortCode, shortCode)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.UrlOriginal,
		&i.ShortCode,
		&i.AccessCount,
		&i.CreatedAt,
	)
	return i, err
}

const incrementAccessCount = `-- name: IncrementAccessCount :exec
UPDATE urls
SET access_count = access_count + 1
WHERE short_code = $1
`

func (q *Queries) IncrementAccessCount(ctx context.Context, shortCode string) error {
	_, err := q.db.ExecContext(ctx, incrementAccessCount, shortCode)
	return err
}

const updateURL = `-- name: UpdateURL :one
UPDATE urls
SET url_original = $2
WHERE short_code = $1
RETURNING id, url_original, short_code, access_count, created_at
`

type UpdateURLParams struct {
	ShortCode   string `json:"short_code"`
	UrlOriginal string `json:"url_original"`
}

func (q *Queries) UpdateURL(ctx context.Context, arg UpdateURLParams) (Url, error) {
	row := q.db.QueryRowContext(ctx, updateURL, arg.ShortCode, arg.UrlOriginal)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.UrlOriginal,
		&i.ShortCode,
		&i.AccessCount,
		&i.CreatedAt,
	)
	return i, err
}
